<link rel="stylesheet" href="/lib/font-awesome/css/font-awesome.min.css">
<link rel="stylesheet" href="/lib/bootstrap/css/bootstrap.min.css">
<link rel='stylesheet' href='/lib/AdminLTE2/css/main.min.css'/>
<link rel="stylesheet" href="/lib/toastr/toastr.css">
<link rel="stylesheet" href="/css/dataurl.min.css">
<link rel="stylesheet" href="/lib/fancybox/jquery.fancybox.css">
<link rel='stylesheet' href='/css/style.min.css'/>